### ISSUE TITLE
Clicking on certain items in TRQI dropdown from 'Seat Request' closes dialog

### ISSUE THREAD

**Issue by timmcallister** [jeff-mccoy/FTSS#47]
See pic: clicking on the highlighted item in this dropdown closes the 'Seat Request' dialog as it is outside the border of the original dialog.
![bug](https://cloud.githubusercontent.com/assets/7793127/11322017/1b6804b4-909c-11e5-9a13-731c1be17a76.png)

**Comment by jeff-mccoy** [comment]
I actually just came across this same issue when building the role request feature.  It should already be fixed in one of the commits I made last week, but haven't pushed to the production side yet.  I'll go back and check to make sure/tag this issue when o find it.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Sat, Nov 21, 2015 at 8:16 PM -0800, "timmcallister" <notifications@github.com<mailto:notifications@github.com>> wrote:


See pic: clicking on the highlighted item in this dropdown closes the 'Seat Request' dialog as it is outside the border of the original dialog.
[bug]<https://cloud.githubusercontent.com/assets/7793127/11322017/1b6804b4-909c-11e5-9a13-731c1be17a76.png>

-
